// Mocks generated by Mockito 5.4.4 from annotations
// in stackoverflow_users_reputation/test/unit/modules/users/domain/usecases/user_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stackoverflow_users_reputation/modules/users/domain/entities/user_entity.dart'
    as _i4;
import 'package:stackoverflow_users_reputation/modules/users/domain/repositories/user_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  @override
  _i3.Future<List<_i4.UserEntity>> getUsers({
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i3.Future<List<_i4.UserEntity>>.value(<_i4.UserEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.UserEntity>>.value(<_i4.UserEntity>[]),
      ) as _i3.Future<List<_i4.UserEntity>>);

  @override
  _i3.Future<void> bookmarkUser(_i4.UserEntity? user) => (super.noSuchMethod(
        Invocation.method(
          #bookmarkUser,
          [user],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeBookmark(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #removeBookmark,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.UserEntity>> getBookmarkedUsers() => (super.noSuchMethod(
        Invocation.method(
          #getBookmarkedUsers,
          [],
        ),
        returnValue: _i3.Future<List<_i4.UserEntity>>.value(<_i4.UserEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.UserEntity>>.value(<_i4.UserEntity>[]),
      ) as _i3.Future<List<_i4.UserEntity>>);

  @override
  _i3.Future<bool> isUserBookmarked(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #isUserBookmarked,
          [userId],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
