// Mocks generated by Mockito 5.4.4 from annotations
// in stackoverflow_users_reputation/test/unit/modules/reputation/presentation/bloc/reputation_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stackoverflow_users_reputation/modules/reputation/domain/entities/reputation_history_entity.dart'
    as _i5;
import 'package:stackoverflow_users_reputation/modules/reputation/domain/repositories/reputation_repository.dart'
    as _i2;
import 'package:stackoverflow_users_reputation/modules/reputation/domain/usecases/reputation_usecases.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReputationRepository_0 extends _i1.SmartFake
    implements _i2.ReputationRepository {
  _FakeReputationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetReputationHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetReputationHistoryUseCase extends _i1.Mock
    implements _i3.GetReputationHistoryUseCase {
  @override
  _i2.ReputationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeReputationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeReputationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ReputationRepository);

  @override
  _i4.Future<List<_i5.ReputationHistoryEntity>> call({
    required int? userId,
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #userId: userId,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<List<_i5.ReputationHistoryEntity>>.value(
            <_i5.ReputationHistoryEntity>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.ReputationHistoryEntity>>.value(
                <_i5.ReputationHistoryEntity>[]),
      ) as _i4.Future<List<_i5.ReputationHistoryEntity>>);
}
