// Mocks generated by Mockito 5.4.4 from annotations
// in stackoverflow_users_reputation/test/unit/modules/users/presentation/bloc/user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stackoverflow_users_reputation/modules/users/domain/entities/user_entity.dart'
    as _i5;
import 'package:stackoverflow_users_reputation/modules/users/domain/repositories/user_repository.dart'
    as _i2;
import 'package:stackoverflow_users_reputation/modules/users/domain/usecases/user_usecases.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetUsersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUsersUseCase extends _i1.Mock implements _i3.GetUsersUseCase {
  @override
  _i2.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.UserRepository);

  @override
  _i4.Future<List<_i5.UserEntity>> call({
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<List<_i5.UserEntity>>.value(<_i5.UserEntity>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.UserEntity>>.value(<_i5.UserEntity>[]),
      ) as _i4.Future<List<_i5.UserEntity>>);
}

/// A class which mocks [BookmarkUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkUserUseCase extends _i1.Mock
    implements _i3.BookmarkUserUseCase {
  @override
  _i2.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.UserRepository);

  @override
  _i4.Future<void> call(_i5.UserEntity? user) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [RemoveBookmarkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveBookmarkUseCase extends _i1.Mock
    implements _i3.RemoveBookmarkUseCase {
  @override
  _i2.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.UserRepository);

  @override
  _i4.Future<void> call(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GetBookmarkedUsersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBookmarkedUsersUseCase extends _i1.Mock
    implements _i3.GetBookmarkedUsersUseCase {
  @override
  _i2.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.UserRepository);

  @override
  _i4.Future<List<_i5.UserEntity>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.UserEntity>>.value(<_i5.UserEntity>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.UserEntity>>.value(<_i5.UserEntity>[]),
      ) as _i4.Future<List<_i5.UserEntity>>);
}
