// Mocks generated by Mockito 5.4.4 from annotations
// in stackoverflow_users_reputation/test/widget/modules/users/presentation/screens/users_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stackoverflow_users_reputation/modules/users/domain/usecases/user_usecases.dart'
    as _i2;
import 'package:stackoverflow_users_reputation/modules/users/presentation/bloc/user_bloc.dart'
    as _i4;
import 'package:stackoverflow_users_reputation/modules/users/presentation/bloc/user_event.dart'
    as _i6;
import 'package:stackoverflow_users_reputation/modules/users/presentation/bloc/user_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetUsersUseCase_0 extends _i1.SmartFake
    implements _i2.GetUsersUseCase {
  _FakeGetUsersUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBookmarkUserUseCase_1 extends _i1.SmartFake
    implements _i2.BookmarkUserUseCase {
  _FakeBookmarkUserUseCase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveBookmarkUseCase_2 extends _i1.SmartFake
    implements _i2.RemoveBookmarkUseCase {
  _FakeRemoveBookmarkUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetBookmarkedUsersUseCase_3 extends _i1.SmartFake
    implements _i2.GetBookmarkedUsersUseCase {
  _FakeGetBookmarkedUsersUseCase_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserState_4 extends _i1.SmartFake implements _i3.UserState {
  _FakeUserState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserBloc extends _i1.Mock implements _i4.UserBloc {
  @override
  _i2.GetUsersUseCase get getUsersUseCase => (super.noSuchMethod(
        Invocation.getter(#getUsersUseCase),
        returnValue: _FakeGetUsersUseCase_0(
          this,
          Invocation.getter(#getUsersUseCase),
        ),
        returnValueForMissingStub: _FakeGetUsersUseCase_0(
          this,
          Invocation.getter(#getUsersUseCase),
        ),
      ) as _i2.GetUsersUseCase);

  @override
  _i2.BookmarkUserUseCase get bookmarkUserUseCase => (super.noSuchMethod(
        Invocation.getter(#bookmarkUserUseCase),
        returnValue: _FakeBookmarkUserUseCase_1(
          this,
          Invocation.getter(#bookmarkUserUseCase),
        ),
        returnValueForMissingStub: _FakeBookmarkUserUseCase_1(
          this,
          Invocation.getter(#bookmarkUserUseCase),
        ),
      ) as _i2.BookmarkUserUseCase);

  @override
  _i2.RemoveBookmarkUseCase get removeBookmarkUseCase => (super.noSuchMethod(
        Invocation.getter(#removeBookmarkUseCase),
        returnValue: _FakeRemoveBookmarkUseCase_2(
          this,
          Invocation.getter(#removeBookmarkUseCase),
        ),
        returnValueForMissingStub: _FakeRemoveBookmarkUseCase_2(
          this,
          Invocation.getter(#removeBookmarkUseCase),
        ),
      ) as _i2.RemoveBookmarkUseCase);

  @override
  _i2.GetBookmarkedUsersUseCase get getBookmarkedUsersUseCase =>
      (super.noSuchMethod(
        Invocation.getter(#getBookmarkedUsersUseCase),
        returnValue: _FakeGetBookmarkedUsersUseCase_3(
          this,
          Invocation.getter(#getBookmarkedUsersUseCase),
        ),
        returnValueForMissingStub: _FakeGetBookmarkedUsersUseCase_3(
          this,
          Invocation.getter(#getBookmarkedUsersUseCase),
        ),
      ) as _i2.GetBookmarkedUsersUseCase);

  @override
  _i3.UserState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUserState_4(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeUserState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.UserState);

  @override
  _i5.Stream<_i3.UserState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.UserState>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.UserState>.empty(),
      ) as _i5.Stream<_i3.UserState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i6.UserEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.UserEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.UserState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.UserEvent>(
    _i7.EventHandler<E, _i3.UserState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i7.Transition<_i6.UserEvent, _i3.UserState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onChange(_i7.Change<_i3.UserState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
